from tkinter import *
from entry_cap import entry_cap
import uuid

def student_form():
    mywindow = Tk()
    def send_data():
        name_data = name.get()
        lastname_data = lastname.get()
        gender_data = gender.get()
        age_data = age.get()
        grade_data = grade.get()
        mail_data = mail.get()
        matricula = uuid.uuid1()
        entry_cap(name_data, matricula.hex, mywindow)


    
    mywindow.geometry("650x550")
    mywindow.title("Regristro de Estudiante")
    mywindow.resizable(False,False)
    mywindow.config(background = "#00ffff")
    main_title = Label(text="Formulario de Registro de Nuevo Estudiante",font=("Calibri",14), bg="#4FCAB5", fg="white", width="550", height="2")
    main_title.pack()
    name_label = Label(text="Nombres:", bg="#00ffff", font="30")
    name_label.place(x=22, y=70)
    lastname_label = Label(text="Apellidos:", bg="#00ffff", font="30")
    lastname_label.place(x=22, y=130)
    gender_label = Label(text="Género:", bg="#00ffff", font="30")
    gender_label.place(x=22, y=190)
    age_label = Label(text="Edad:", bg="#00ffff", font="30")
    age_label.place(x=22, y=250)
    grade_label = Label(text="Curso:",  bg="#00ffff", font="30")
    grade_label.place(x=22, y=310)
    mail_label = Label(text="Correo del Padre:", bg="#00ffff", font="30")
    mail_label.place(x=22, y=380)
    name = StringVar()
    lastname = StringVar()
    gender = StringVar()
    age = StringVar()
    grade = StringVar()
    mail = StringVar()
    name_entry = Entry(textvariable=name, width="30", font="30")
    lastname_entry = Entry(textvariable=lastname, width="30", font="30")
    gender_entry = Entry(textvariable=gender, width="30", font="30")
    age_entry = Entry(textvariable=age, width="20", font="30")
    grade_entry = Entry(textvariable=grade, width="30", font="30")
    mail_entry = Entry(textvariable=mail, width="30", font="30")

    name_entry.place(x=22, y=100)
    lastname_entry.place(x=22, y=160)
    gender_entry.place(x=22, y=220)
    age_entry.place(x=22, y=280)
    grade_entry.place(x=22, y=340)
    mail_entry.place(x=22, y=410)
    submit_btn = Button(mywindow, text="Registrar", font=("Calibri",15), command=send_data, width="20", height="2", bg="#00CD63")
    submit_btn.place(x=22, y=460)
    mywindow.mainloop()